language: java

script: ./build.sh jar testTravis

cache:
  directories:
    - $HOME/.m2/repository

matrix:
  include:
    - jdk: openjdk10
      dist: trusty
      group: edge
      sudo: required
      before_script:
        - "cd h2"
        - "echo $JAVA_OPTS"
        - "export JAVA_OPTS=-Xmx512m"
    - jdk: oraclejdk8
      dist: trusty
      group: edge
      sudo: required
      before_script:
        - "cd h2"
        - "echo $JAVA_OPTS"
        - "export JAVA_OPTS=-Xmx512m"
    - jdk: openjdk7
      dist: trusty
      group: edge
      sudo: required
      before_script:
        - "cd h2"
